openapi: 3.0.3
info:
  title: OKD - Open Education API
  description: "OpenAPI specification for the Open Education API, used in the OKD.\n\
    <br/>\nNOTE:This is a subset of the OOAPI that is used in the \"MBO-OKD\" project\
    \ (sponsored by npuls/mbo-digitaal in the netherlands). This project uses the\
    \ \"nl-okd\" consumer \n<br/>\n<figure>\n\t<a target=\"_blank\" href=\"OOAPIv5_model.png\"\
    >\n  <img src=\"OOAPIv5_model.png\" alt=\"OOAPI informatiemodel dat de OOAPI specificatie\
    \ voedt\" width=\"70%\" class=\"img-responsive\">\n  </a>\n  <figcaption> OOAPI\
    \ informatiemodel dat de OOAPI specificatie voedt (klik om te vergroten)</figcaption>\n\
    </figure>\n\nHet model geeft een overzicht van hoe de objecten waarop de API is\
    \ gespecificeerd zijn gerelateerd. Het overkoepelende concept educations wordt\
    \ niet gevonden in de eindpunten van de API. De kleinere concepten van programOffering,\
    \ courseOffering en conceptOffering worden allemaal gevonden in het offering eindpunt.\
    \ De verschillende types van associatie kunnen allemaal worden gevonden in het\
    \ association eindpunt.\n\nHet originele bestand voor dit model kan <a target=\"\
    _blank\" href=\"OOAPIv5_model_v0.5.drawio\">hier</a> worden gevonden\n\nHet program\
    \ relations object wordt niet gevonden als een apart eindpunt, maar relaties tussen\
    \ programma's kunnen worden gevonden binnen het program eindpunt door dat eindpunt\
    \ uit te breiden.\n\nInformatie over eerdere bijeenkomsten en presentaties kan\
    \ <a target=\"_blank\" href=\"https://github.com/open-education-api/notulen\"\
    >hier</a> worden gevonden\n\nInformatie over het EDU-API model dat ook werd gebruikt\
    \ voor deze api wordt <a target=\"_blank\" href=\"eduapi.png\">hier</a> getoond\n"
  contact:
    name: Kees van Ginkel
    email: kees.van.ginkel@topicus.nl
  version: 0.9.0
  x-logo:
    url: ../logo.png
servers:
- url: http://okd.eduapi.nl/v5
  description: OKD demo implementation
tags:
- name: service metadata
  description: |
    The service API provides additional metadata needed to make the OOAPI fit for this organization.

        Voor de OKD: De service API biedt aanvullende metadata die nodig is om te zien welke versie van de ooapi en OKD ondersteund wordt.
- name: documents
  description: |
    The documents API provides access to the documents in a binary format

        Voor de OKD: De documenten API biedt toegang tot de documenten in een binaire vorm en de mogenlijkheid om de inhoud van documenten te updaten. Het aanbieden van documenten gaat via andere endpoints.
- name: associations
  description: "De associations API biedt informatie over de inschrijvingen van personen\
    \ bij programma's, cursussen en componenten.\n    \n    Voor de OKD: In het Nederlandse\
    \ onderwijssysteem zijn dit de inschrijving-verbintenis en de inschrijving voor\
    \ BPV of examens\n"
- name: persons
  description: |
    The persons API provides information about persons related to an organization.

        Voor de OKD: De personen API geeft de mogenlijkheid om een bestand aan te bieden die aan de persoon gelinkt is.

        Ook kan er additionele informatie van een persoon opgehaald worden. (zoeken op studentnummer of id)
- name: offerings
  description: |
    The offerings API provides information about offerings which have a global timeframe, e.g. a period to which students can enroll.

        Voor de OKD: De offerings API biedt informatie over de onderwijsaanbod die een instelling aanbiedt. een onderdeel zijn componentOfferings, die in de OKD als examens of toetsen worden gebruikt.
paths:
  /:
    get:
      tags:
      - service metadata
      summary: GET /
      description: |
        Get metadata for the service.

        note:
        - This endpoint does not require authentication.
        - This endpoint should be implemented by the DMS and all components
      operationId: listServiceMetaData
  /persons:
    get:
      tags:
      - persons
      summary: GET /persons
      description: |
        Get a list of persons, select by primaryCode/Student nummer

        note:
        - This endpoint should be implemented by the SIS component, so that the DMS can retrieve person information (flow-7)
      operationId: listPersons
      security:
      - oAuthFlows:
        - okd:studentinfo
  /persons/{personId}:
    get:
      tags:
      - persons
      summary: "GET /persons/{personId}"
      description: |
        Get a single person

        note:
        - This endpoint should be implemented by the SIS component, so that the DMS can retrieve person information (flow-7)
      operationId: listPersonById
      security:
      - oAuthFlows:
        - okd:studentinfo
    post:
      tags:
      - persons
      summary: "POST /persons/{personId}"
      description: |
        POST a document for a person

        note:
        - This endpoint should be implemented by the DMS component, so that the components can upload documents for a person (flow 1,2,3,4)
        - the call is a multipart/form-data call with 2 parts: metadata (json) and file (binary).
      operationId: postDocumentOnPersonById
      security:
      - oAuthFlows:
        - okd:alldocuments
  /offerings/{offeringId}:
    post:
      tags:
      - offerings
      summary: "POST /offerings/{offeringId}"
      description: "POST an file on the offerings.\n\n    For the OKD: Plaats een\
        \ document bij een zitting (offering). bv het zittingsverslag. \n    Documenten\
        \ speciaal voor een persoon (beoordeling etc) moeten op de associatie van\
        \ deze persoon geplaats worden.\n\nnote:\n- This endpoint should be implemented\
        \ by the DMS component, so that the components can upload documents for a\
        \ offering.\n- the call is a multipart/form-data call with 2 parts: metadata\
        \ (json) and file (binary).\n"
      operationId: postFileOnOfferingById
      security:
      - oAuthFlows:
        - okd:alldocuments
        - okd:examdocuments
  /documents/{documentId}:
    get:
      tags:
      - documents
      summary: "GET /documents/{documentId}"
      description: |
        Get the document stored in the DMS.
        This can be done in 2 ways:
        1. Get the metadata of a document (request content-type application/json)
        2. Get the binary data from a document. (request content-type application/octet-stream)

        note:
        - This endpoint should be implemented by the DMS component, so that the components can retrieve documents. (flow-x)
        - The documentId is the ID returned by the DMS when the document was uploaded.
      operationId: getDocumentById
      security:
      - oAuthFlows:
        - okd:alldocuments
        - okd:examdocuments
        - okd:bpvdocuments
        - okd:graduationdocuments
        - okd:enrollmentderollment
    delete:
      tags:
      - documents
      summary: "DELETE /documents/{documentId}"
      description: |
        Delete the document stored in the DMS.

        note:
        - This endpoint should be implemented by the DMS component, so that the components can delete documents. (flow-z)
        - This endpoint should be implemented by the components, so that the DMS can inform that the document is destroyed. (flow-6)
        - The documentId is the ID returned by the DMS when the document was uploaded.
        - oAuthFlows okd:destroyednotification is only for the DMS to inform the components that a document is destroyed.
      operationId: deleteDocumentById
      security:
      - oAuthFlows:
        - okd:alldocuments
        - okd:examdocuments
        - okd:bpvdocuments
        - okd:graduationdocuments
        - okd:enrollmentderollment
        - okd:destroyednotification
    patch:
      tags:
      - documents
      summary: Upload document to replace the content of an existing document
      description: |
        Update the document stored in the DMS.

        note:
        - This endpoint should be implemented by the DMS component, so that the components can update documents. (flow-y)
        - The documentId is the ID returned by the DMS when the document was uploaded.
        - The call is a application/octet-stream call with the binary file to upload
        - no meta data updates is possible with this call.
      operationId: updateDocument
      security:
      - oAuthFlows:
        - okd:alldocuments
        - okd:examdocuments
        - okd:bpvdocuments
        - okd:graduationdocuments
        - okd:enrollmentderollment
  /associations/{associationId}:
    get:
      tags:
      - associations
      summary: "GET /associations/{associationId}"
      description: |
        Get a single association (OKD: inschrijving/verbintenis)

        note:
        - This endpoint should be implemented by the SIS component, so that the DMS can retrieve a persons verbintenis information
      operationId: listAssociationById
      security:
      - oAuthFlows:
        - okd:studentinfo
    post:
      tags:
      - associations
      summary: "POST /associations/{associationId}"
      description: "POST a document with the association (inschrijving) metadata.\
        \ \n\n    For the OKD: Plaats een document bij een verbintenis. \n\nnote:\n\
        - This endpoint should be implemented by the DMS component, so that the components\
        \ can upload documents for a association/verbintenis.\n- the call is a multipart/form-data\
        \ call with 2 parts: metadata (json) and file (binary).\n- hoewel de ooapi\
        \ meer states kent gebruiken we alleen \"associated\", \"finished\".\n"
      operationId: postFileOnAssociationById
      security:
      - oAuthFlows:
        - okd:alldocuments
        - okd:enrollmentderollment
    patch:
      tags:
      - associations
      summary: "PATCH /associations/{associationId}"
      description: "Update the status or result of an enrollment. Other elements of\
        \ the association object COULD \nalso be PATCHED. But are not likely and have\
        \ therefor not been included in this endpoint.\nImplementation of the PATCH\
        \ activity is based on use PATCH with JSON Merge Patch standard, \na specialized\
        \ media type `application/merge-patch+json` for partial resource representation\
        \ \nto update parts of resource objects.\n\n    Voor OKD: Update de status\
        \ of het resultaat van een inschrijving. Eigenlijk word alleen het veld \"\
        state\" verandert om aan te geven dat de verbintenis beeindigt is.\n    hoewel\
        \ de ooapi meer states kent gebruiken we alleen \"associated\", \"finished\"\
        .\n\nNote:\n  - This endpoint should be implemented by the DMS component,\
        \ so that the Uitschrijven component can update a persons verbintenis information\
        \ (flow 5)\n"
      operationId: partialUpdateAssociationById
      security:
      - oAuthFlows:
        - okd:enrollmentderollment
components:
  securitySchemes:
    oAuthFlows:
      type: oauth2
      description: |
        This API uses oauth Cleint credentials for server to server #/components/schemas/EducationSpecification
      flows:
        clientCredentials:
          tokenUrl: https://example.nl/oauth2/token
          scopes:
            okd:alldocuments: "flow 1,2,3,4,x,y,z"
            okd:examdocuments: "flow 2,x,y,z"
            okd:bpvdocuments: "flow 3,x,y,z"
            okd:graduationdocuments: "flow 4,x,y,z"
            okd:enrollmentderollment: "flow 1,5"
            okd:destroyednotification: flow 6
            okd:studentinfo: flow 7
